quarkus:
  http:
    port: 8010
  hibernate-orm:
    database:
      generation: drop-and-create
  datasource:
    db-kind: h2
    username: nttdata2026
    jdbc:
      url: jdbc:h2:mem:ecommerce
      max-size: 25
  rest-client:
    api-products:
      url: https://fakestoreapi.com
      scope: jakarta.inject.Singleton
      tls-configuration-name: tls-disabled
  tls:
    tls-disabled:
      trust-all: true
      hostname-verification-algorithm: NONE